Repository NanoComp/meep, pull requests merged in 2019-02, with the labels that each got.

#698 tutorial for eigenmode source in oblique waveguide
  README.md
  doc/docs/Python_Tutorials/Eigenmode_Source.md
  doc/docs/Python_User_Interface.md
  doc/docs/Scheme_Tutorials/Eigenmode_Source.md
  doc/docs/Scheme_User_Interface.md
  doc/docs/images/eigenmode_source.png
  doc/docs/images/oblique_source_multimode.png
  doc/docs/images/oblique_source_singlemode.png
  doc/docs/index.md
  mkdocs.yml
  python/examples/oblique-source.py
  scheme/examples/oblique-source.ctl
Labels: documentation

#696 fix bug in SWIG wrapper for dft_near2far::flux and update tutorial
  README.md
  doc/docs/Python_Tutorials/GDSII_Import.md
  doc/docs/Python_Tutorials/Near_to_Far_Field_Spectra.md
  doc/docs/Scheme_Tutorials/Near_to_Far_Field_Spectra.md
  doc/docs/Scheme_User_Interface.md
  doc/docs/index.md
  python/examples/antenna-radiation.py
  scheme/examples/antenna-radiation.ctl
  scheme/meep-ctl-swig.hpp
  scheme/meep.cpp
  scheme/meep.scm.in
Labels: bug, documentation

#724 Fix bug in solve-cw.py
  python/examples/solve-cw.py
Labels: bug

#725 Update build script in docs
  doc/docs/Build_From_Source.md
Labels: documentation

#726 add 3 FAQs and update docs
  doc/docs/Download.md
  doc/docs/FAQ.md
  doc/docs/Python_Tutorials/Ring_Resonator_in_Cylindrical_Coordinates.md
  doc/docs/Python_User_Interface.md
  doc/docs/Scheme_Tutorials/Ring_Resonator_in_Cylindrical_Coordinates.md
  doc/docs/Scheme_User_Interface.md
Labels: documentation

#735 binary grating tutorial for Scheme
  doc/docs/Scheme_Tutorials/Mode_Decomposition.md
  scheme/examples/binary_grating.ctl
  scheme/examples/binary_grating_oblique.ctl
  scheme/examples/binary_grating_phasemap.ctl
  scheme/examples/mode-decomposition.ctl
Labels: documentation

#742 liquid crystal polarization grating tutorial for Scheme
  doc/docs/Python_Tutorials/Mode_Decomposition.md
  doc/docs/Scheme_Tutorials/Mode_Decomposition.md
  python/examples/polarization_grating.py
  scheme/examples/polarization_grating.ctl
Labels: documentation
