Repository NanoComp/meep, pull requests merged in 2020-09, with the labels that each got.

#1337 minor updates to docs
  doc/docs/FAQ.md
  doc/docs/Python_Tutorials/Basics.md
  doc/docs/Python_Tutorials/Custom_Source.md
  doc/docs/Python_User_Interface.md
  doc/docs/Python_User_Interface.md.in
  doc/docs/Scheme_Tutorials/Basics.md
  doc/docs/Scheme_Tutorials/Custom_Source.md
  doc/docs/images/stochastic_emitter_line_normalized_flux_comparison.png
  doc/docs/images/stochastic_emitter_normalized_flux_comparison.png
  doc/docs/images/stochastic_emitter_trials.png
Labels: documentation

#1344 ￼ more accurate language composition statistics
  .gitattributes
Labels: documentation

#1350 minor improvements to docs
  .gitattributes
  doc/docs/Exploiting_Symmetry.md
  doc/docs/FAQ.md
  doc/docs/Field_Functions.md
  doc/docs/Introduction.md
  doc/docs/Materials.md
  doc/docs/Python_Developer_Information.md
  doc/docs/Python_Tutorials/AdjointSolver.md
  doc/docs/Python_Tutorials/Basics.md
  doc/docs/Python_Tutorials/Eigenmode_Source.md
  doc/docs/Scheme_Tutorials/Basics.md
  doc/docs/Scheme_Tutorials/Eigenmode_Source.md
  doc/docs/The_Run_Function_Is_Not_A_Loop.md
  doc/docs/Units_and_Nonlinearity.md
  doc/docs/Yee_Lattice.md
  python/examples/differential_cross_section.py
Labels: documentation

#1359 tweaks to graphene FAQ
  doc/docs/FAQ.md
Labels: documentation

#1361 provide details regarding convergence properties of deterministic method involving point-dipole sources to LED tutorial
  doc/docs/Python_Tutorials/Custom_Source.md
Labels: documentation

#1360 minor fixes and tweaks to docs
  doc/docs/FAQ.md
  doc/docs/Field_Functions.md
  doc/docs/Parallel_Meep.md
  doc/docs/Python_Tutorials/Mode_Decomposition.md
  doc/docs/Python_Tutorials/Near_to_Far_Field_Spectra.md
  doc/docs/Python_User_Interface.md
  doc/docs/Subpixel_Smoothing.md
  python/examples/binary_grating_oblique.py
  python/geom.py
  python/simulation.py
Labels: documentation

#1364 fix memory leak in python/meep.i
  python/meep.i
Labels: bug

#1367 remove unused function output_mode_fields
  doc/docs/Mode_Decomposition.md
  src/dft.cpp
  src/meep.hpp
Labels: enhancement

#1347 clarify computation of reflection coefficient S11 in directional-coupler tutorial
  doc/docs/Python_Tutorials/GDSII_Import.md
  doc/docs/images/coupler_refl_S11_S12.png
Labels: documentation

#1378 replace Numpy matrix with array in test geom.py
  python/tests/geom.py
Labels: enhancement
