Repository NanoComp/meep, pull requests merged in 2021-09, with the labels that each got.

#1748 minor improvements to docs
  README.md
  doc/docs/FAQ.md
  doc/docs/Python_Tutorials/Adjoint_Solver.md
  doc/docs/Python_Tutorials/Mode_Decomposition.md
  doc/docs/Python_User_Interface.md
  doc/docs/Subpixel_Smoothing.md
  doc/docs/index.md
  python/examples/binary_grating_oblique.py
  python/simulation.py
Labels: documentation

#1749 support adjoint gradients in cylindrical coordinate
  python/Makefile.am
  python/adjoint/optimization_problem.py
  python/meep.i
  python/simulation.py
  python/tests/test_adjoint_cyl.py
  src/meepgeom.cpp
  src/meepgeom.hpp
  src/near2far.cpp
Labels: enhancement

#1745 set the default number of threads to one for multi-threading
  doc/docs/Build_From_Source.md
  doc/docs/Parallel_Meep.md
  python/simulation.py
  src/meep.hpp
  src/meep/vec.hpp
  src/mympi.cpp
Labels: enhancement, documentation

#1733 loop tiling for step_update_edhb
  doc/docs/Python_User_Interface.md
  python/simulation.py
  src/fields.cpp
  src/meep.hpp
  src/step_db.cpp
  src/update_eh.cpp
Labels: enhancement

#1740 Revamped add fields::dft_fields_norm2
  python/adjoint/optimization_problem.py
  python/meep.i
  python/simulation.py
  python/tests/test_adjoint_cyl.py
  python/tests/test_adjoint_solver.py
  src/dft.cpp
  src/meep.hpp
  src/meep/mympi.hpp
  src/mympi.cpp
Labels: enhancement

#1760 additional documentation for MaterialGrid
  doc/docs/Python_User_Interface.md
  doc/docs/images/material_grid.png
  python/geom.py
  python/tests/test_material_grid.py
Labels: documentation

#1759 markdown documentation for stop_when_dft_decayed
  doc/docs/Python_User_Interface.md
  doc/docs/Python_User_Interface.md.in
  python/simulation.py
Labels: documentation

#1770 raise an exception if eigenmode not found
  src/mpb.cpp
Labels: enhancement

#1768 unit test for MaterialGrid with symmetry
  python/Makefile.am
  python/tests/test_adjoint_solver.py
  python/tests/test_material_grid.py
Labels: enhancement

#1769 fix off-by-one bug in dimensions of fixed-resolution MaterialGrid for adjoint-solver functions
  python/adjoint/basis.py
  python/adjoint/filters.py
  python/tests/test_adjoint_solver.py
Labels: bug, enhancement
