Repository NanoComp/meep, pull requests merged in 2021-05, with the labels that each got.

#1539 computing the normal vector to an interface for a MaterialGrid using analytic gradient
  python/tests/material_grid.py
  src/fields.cpp
  src/meep_internals.hpp
  src/meepgeom.cpp
  src/meepgeom.hpp
Labels: enhancement

#1563 instructions for specifying floating-point precision of fields/materials arrays
  doc/docs/Build_From_Source.md
  doc/docs/Parallel_Meep.md
  doc/docs/Subpixel_Smoothing.md
Labels: documentation

#1566 instructions for reducing runtime of split_chunks_evenly=False cell partitioning
  doc/docs/Materials.md
  doc/docs/Parallel_Meep.md
  doc/docs/Python_Tutorials/Adjoint_Solver.md
  doc/docs/Python_User_Interface.md
  doc/docs/Subpixel_Smoothing.md
  python/simulation.py
  src/meepgeom.cpp
Labels: documentation

#1574 fix segmentation fault in material_grids_addgradient of adjoint solver
  src/meepgeom.cpp
Labels: bug

#1577 pass binary-tree partition to structure constructor
  python/meep.i
  python/simulation.py
  src/meep.hpp
  src/structure.cpp
  src/structure_dump.cpp
Labels: enhancement

#1569 WIP: Initial version of JAX-Meep wrapper
  python/Makefile.am
  python/adjoint/__init__.py
  python/adjoint/jax/__init__.py
  python/adjoint/jax/utils.py
  python/adjoint/jax/wrapper.py
  python/tests/adjoint_jax.py
  python/tests/utils.py
Labels: enhancement
