Repository NanoComp/meep, pull requests merged in 2021-07, with the labels that each got.

#1653 preliminaries for tiled timestepping
  src/meep_internals.hpp
  src/step_db.cpp
  src/step_generic.cpp
  src/update_eh.cpp
Labels: enhancement

#1662 update binary-grating tutorial to mention glancing-angle waves and PMLs
  doc/docs/Python_Tutorials/Mode_Decomposition.md
  doc/docs/Scheme_Tutorials/Mode_Decomposition.md
Labels: documentation

#1665 Add pretty-printing to meep.BinaryPartition
  python/simulation.py
Labels: enhancement

#1666 Display coverage badge in README.md
  README.md
  codecov.yml
Labels: enhancement

#1669 Raise runtime error in get_dft_array and output_dft if monitor's SWIG object does not exist
  python/simulation.py
Labels: enhancement

#1681 Assign ranks to leaves of binary partition in depth-first order
  src/structure.cpp
Labels: bug

#1675 Enable single-precision floating point for DFT fields arrays
  doc/docs/Build_From_Source.md
  src/dft.cpp
  src/meep.hpp
  src/stress.cpp
Labels: enhancement

#1672 Document the number of processes/threads for MPI/OpenMP tests
  doc/docs/Build_From_Source.md
Labels: documentation

#1688 Expose floating-point precision in Python
  doc/docs/Build_From_Source.md
  python/meep.i
Labels: enhancement

#1698 Enable single-precision floating point unit tests for CI
  .github/workflows/build-ci.yml
  python/tests/test_3rd_harm_1d.py
  python/tests/test_adjoint_jax.py
  python/tests/test_adjoint_solver.py
  python/tests/test_array_metadata.py
  python/tests/test_cavity_arrayslice.py
  python/tests/test_cavity_farfield.py
  python/tests/test_chunks.py
  python/tests/test_dispersive_eigenmode.py
  python/tests/test_divide_mpi_processes.py
  python/tests/test_eigfreq.py
  python/tests/test_field_functions.py
  python/tests/test_get_point.py
  python/tests/test_holey_wvg_bands.py
  python/tests/test_holey_wvg_cavity.py
  python/tests/test_mode_coeffs.py
  python/tests/test_multilevel_atom.py
  python/tests/test_pw_source.py
  python/tests/test_refl_angular.py
  python/tests/test_ring.py
  python/tests/test_ring_cyl.py
  python/tests/test_simulation.py
  python/tests/test_user_defined_material.py
  python/tests/test_wvg_src.py
  tests/aniso_disp.cpp
  tests/array-slice-ll.cpp
  tests/cyl-ellipsoid-ll.cpp
  tests/h5test.cpp
  tests/harmonics.cpp
  tests/near2far.cpp
  tests/pml.cpp
  tests/symmetry.cpp
Labels: enhancement

#1703 fix step_* to allow tiled (is,ie)
  src/step_generic.cpp
Labels: bug
