Repository NanoComp/meep, pull requests merged in 2022-06, with the labels that each got.

#2103 tutorial for triangular/hexagonal lattice diffracted orders
  doc/docs/Python_Tutorials/Mode_Decomposition.md
  doc/docs/images/triangular_lattice.png
  python/examples/grating2d_triangular_lattice.py
Labels: documentation

#2082 unit test and tutorial for LDOS in planar cavity using cylindrical coordinates
  doc/docs/Python_Tutorials/Local_Density_of_States.md
  doc/docs/images/planar_cavity_purcell_enhancement.png
  python/examples/planar_cavity_ldos.py
  python/tests/test_ldos.py
Labels: enhancement, documentation

#2114 fix bug in mode coefficients with `DiffractedPlanewave` and nonzero `k_point`
  python/tests/test_mode_decomposition.py
  src/mpb.cpp
Labels: bug, enhancement

#2095 Fix FourierFields adjoint for D and B fields in isotropic media
  python/tests/test_adjoint_solver.py
  src/dft.cpp
Labels: bug, enhancement

#2120 fix Bloch-periodic boundary condition in unit test for mode decomposition and triangular lattice
  python/tests/test_mode_decomposition.py
Labels: bug
