Repository NanoComp/meep, pull requests merged in 2023-01, with the labels that each got.

#2365 Tutorial for adjoint optimization of broadband waveguide mode converter with minimum feature size
  doc/docs/Python_Tutorials/Adjoint_Solver.md
  doc/docs/images/mode_converter_objfunc_hist.png
  doc/docs/images/mode_converter_refl_tran_spectra.png
  doc/docs/images/mode_converter_sim_layout.png
  python/examples/adjoint_optimization/mode_converter.py
Labels: adjoint optimization

#2373 Additional results and updates to adjoint-optimization tutorial involving waveguide mode converter
  doc/docs/Python_Tutorials/Adjoint_Solver.md
  doc/docs/images/mode_converter_designs.png
  doc/docs/images/mode_converter_worst_case_refl_tran.png
Labels: documentation

#2382 Fix bug in step-db update equations in cylindrical coordinates for `m=±1`
  python/tests/test_ldos.py
  src/step_db.cpp
Labels: bug

#2385 subpixel averaging note
  doc/docs/Python_User_Interface.md
Labels: documentation
