Repository NanoComp/meep, pull requests merged in 2023-02, with the labels that each got.

#2387 Add type hints and more details on use of subpixel smoothing to tutorial on adjoint optimization
  doc/docs/Python_Tutorials/Adjoint_Solver.md
  python/examples/adjoint_optimization/mode_converter.py
Labels: documentation

#2395 Add type hints for `MaterialGrid` class
  python/geom.py
Labels: documentation

#2392 Check for invalid sources at r=0 in cylindrical coordinates
  python/tests/test_adjoint_cyl.py
  src/sources.cpp
Labels: enhancement

#2394 memory leak fix; Py_XDCREF amp_func set to NULL
  python/meep.i
  python/tests/test_source.py
Labels: bug

#2383 Fix bug for z-PML in cylindrical coordinates for `m` = 0, ±1
  python/Makefile.am
  python/tests/test_adjoint_cyl.py
  python/tests/test_pml_cyl.py
  src/update_eh.cpp
  tests/cylindrical.cpp
Labels: bug

#2402 Add unit test for step-db field update for `|m| > 1` simulation in cylindrical coordinates
  python/tests/test_pml_cyl.py
Labels: unit tests

#2404 Remove unnecessary long-duration source from LED extraction-efficiency tutorial in cylindrical coordinates
  doc/docs/Python_Tutorials/Local_Density_of_States.md
  python/examples/extraction_eff_ldos.py
Labels: documentation

#2411 Update tutorial for third-order nonlinearity
  doc/docs/Python_Tutorials/Third_Harmonic_Generation.md
  doc/docs/images/3rd-harm-1d-flux.png
  doc/docs/images/3rd-harm-1d-vs-chi.png
  python/examples/3rd-harm-1d.ipynb
  python/examples/3rd-harm-1d.py
Labels: documentation
